### ISSUE TITLE
UTS Spatial Breakdown Structure does not validate in updated bSI Validation Service

### ISSUE THREAD

**Issue by RickBrice** [jwouellette/TPF-5_372-Unit_Test_Suite#14]
I've been building models using the UTS spatial breakdown structure. When run through the updated bSI Validation Service, there are multiple errors regarding the spatial breakdown.

For example, the UTS has IfcBridgePart.SUPERSTRUCTURE and IfcBridgePart.SUBSTRUCTURE are aggregated to the IfcBridge. The validation service says they should be part of IfcSpace. The documentation for IfcSpace seems to support this https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcSpace.htm

I'm getting validation errors throughout the entire spatial breakdown based on the UTS.

Is anyone experiencing the same?

**Comment by SergejMuhic** [comment]
Validation services certainly has some false evaluations there. The documentation says that `IfcSpace` can only be decomposed into another `IfcSpace`.

![image](https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/assets/16683597/501da292-2abb-4a85-9638-580333421c49)

**Comment by RickBrice** [comment]
Here is an example for a 1-span bridge. It seems like the validation service doesn't like anything to Superstructure, Substructure, Abutments, Foundation.

I'm entirely open to the possibility that I've got it wrong.

[PGSuper1.ifc.txt](https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/files/15112781/PGSuper1.ifc.txt)

![image](https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/assets/37087370/48386e09-97ce-4b56-80eb-69e9af46cccc)

**Comment by SergejMuhic** [comment]
Alright, so the problem are `IfcBridgePart` decomposed by `IfcBridgePart`. That csv table does not allow it (for whatever reason). The definition below was submitted to bSI by the IFC Bridge project but apparently they chose to ignore it.

![image](https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/assets/16683597/576a414a-8366-476b-aed1-ea6734a1f7f2)

**Comment by TLiebich** [comment]
but this should be an error in the validation service, bridge parts (and any facility part) should be able to be decomposed into other bridge parts (same applies to the even stricter building spatial hierarchy, where a building can be decomposed into other buildings (e.g. acting as building sections). @RickBrice best you file it as an error to the validation service team.

**Comment by evandroAlfieri** [comment]
Thanks for finding it. We copied the general usages from the spatial decomposition template...which obviously requires fixing too. I'm on it (both docs and vs rule)

**Comment by RickBrice** [comment]
Fixed - see https://github.com/buildingSMART/validate/issues/61
